// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdig9sQiqwukx7SlGEdlC-S_WMl558Iqs',
    appId: '1:808532346102:web:6abbd11f9efd345d6dd8d7',
    messagingSenderId: '808532346102',
    projectId: 'pedometer-d8cdc',
    authDomain: 'pedometer-d8cdc.firebaseapp.com',
    databaseURL: 'https://pedometer-d8cdc-default-rtdb.firebaseio.com',
    storageBucket: 'pedometer-d8cdc.appspot.com',
    measurementId: 'G-9T2SZXG07E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDulINDbeK5OtALK2YHEHUOJ-nNW6TSpx0',
    appId: '1:808532346102:android:76166709ba1596286dd8d7',
    messagingSenderId: '808532346102',
    projectId: 'pedometer-d8cdc',
    databaseURL: 'https://pedometer-d8cdc-default-rtdb.firebaseio.com',
    storageBucket: 'pedometer-d8cdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN48gq-IAA0u470Wb_8hW0Wf7jqrYQGzQ',
    appId: '1:808532346102:ios:a8dac3dcbeca54806dd8d7',
    messagingSenderId: '808532346102',
    projectId: 'pedometer-d8cdc',
    databaseURL: 'https://pedometer-d8cdc-default-rtdb.firebaseio.com',
    storageBucket: 'pedometer-d8cdc.appspot.com',
    androidClientId: '808532346102-kqe29rv31uvmvu81kvpcf267q4lvo9vk.apps.googleusercontent.com',
    iosClientId: '808532346102-gjocgc80d4m1dqed8eev4b99qpa2i4kj.apps.googleusercontent.com',
    iosBundleId: 'com.pedometer.steptracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN48gq-IAA0u470Wb_8hW0Wf7jqrYQGzQ',
    appId: '1:808532346102:ios:56fae831e65589686dd8d7',
    messagingSenderId: '808532346102',
    projectId: 'pedometer-d8cdc',
    databaseURL: 'https://pedometer-d8cdc-default-rtdb.firebaseio.com',
    storageBucket: 'pedometer-d8cdc.appspot.com',
    androidClientId: '808532346102-kqe29rv31uvmvu81kvpcf267q4lvo9vk.apps.googleusercontent.com',
    iosClientId: '808532346102-1088lhs0h2ojk915e1f710ioo64onh0a.apps.googleusercontent.com',
    iosBundleId: 'com.pedometer.steptracker.RunnerTests',
  );
}
